### ISSUE TITLE
BlurView doesn't provide dynamic blur for BottomSheetDialogFragment

### ISSUE THREAD

**Issue by hmmmk** [Dimezis/BlurView#216]
I'm trying to make dynamic blur for a BottomSheetDialog fragment. But the thing is, that BlurView correctly takes snapshot of underlying content and blurs it, but only statically. When I'm trying to move my bottom sheet fragment up and down, blur remains the same, and I want to make it to change when bottom sheet is moving. 

Here is how I enable it in the kotlin code:

```
val rootView = requireActivity().window.decorView as ViewGroup
            bgView.setupWith(rootView)
                .setBlurRadius(10f)
                .setBlurAutoUpdate(true)
```

In the XML layout of BottomSheetDialogFragment,  BlurView is just top element of all hierarchy.

**Comment by Dimezis** [comment]
I have a suspicion about the root cause.
It would help if you could share a sample project

**Comment by hmmmk** [comment]
@Dimezis can I invite you to a closed repo with the project itself? I think it's better to you to check this one in real-case scenario. I will point to the files where I set up BlurView

**Comment by Dimezis** [comment]
Sure, that would work for me too

**Comment by hmmmk** [comment]
@Dimezis sent an invite. The BlurView is used in PurchaseFragmentBottomSheet.kt at line 101

**Comment by hmmmk** [comment]
@Dimezis any updates on this issue?

**Comment by Dimezis** [comment]
@hmmmk I am not able to go through the signup process in your app, please just extract the problematic place into a separate example project, or provide a simple way to reproduce the issue in this project.

**Comment by hmmmk** [comment]
@Dimezis okay, I made a branch called blurtest. If you build this branch it will open screen where you should just press on a button with a big heart, it will open BottomSheetFragment, and you'll see the issue

**Comment by Dimezis** [comment]
I don't see the bottom sheet
![Screenshot_20240725_102443](https://github.com/user-attachments/assets/b467fae8-3bbb-47a7-84ce-a8ff2ef42742)

**Comment by hmmmk** [comment]
@Dimezis 
![telegram-cloud-photo-size-2-5264830719312648738-y](https://github.com/user-attachments/assets/287dbe1f-86f0-4839-bc6a-cb4de7c50fc9)
Go to the first page and press on the button that I highlited on a screenshot

**Comment by Dimezis** [comment]
Version 2.0.5 should fix this issue.
But you also have a different problem - you select a `rootView` that doesn't include the bottom bar, so it's not getting blurred.

**Comment by Dimezis** [comment]
>But I select rootView of the whole activity, how it doesn't include bottom bar?

You don't. Well, not on this branch anyway.
This code from your first post is nowhere to be seen in your project.
```Kotlin
val rootView = requireActivity().window.decorView as ViewGroup
bgView.setupWith(rootView)
```

Your setup looks like this instead:

```Kotlin
val rootView = requireParentFragment().requireParentFragment().requireParentFragment().view as ViewGroup
bgView.setupWith(rootView)
```

**Comment by hmmmk** [comment]
> > But I select rootView of the whole activity, how it doesn't include bottom bar?
> 
> You don't. Well, not on this branch anyway. This code from your first post is nowhere to be seen in your project.
> 
> ```kotlin
> val rootView = requireActivity().window.decorView as ViewGroup
> bgView.setupWith(rootView)
> ```
> 
> Your setup looks like this instead:
> 
> ```kotlin
> val rootView = requireParentFragment().requireParentFragment().requireParentFragment().view as ViewGroup
> bgView.setupWith(rootView)
> ```

Yep, you right. I forgot about this. But anyway, I tried to put 2.0.5 and it's still not working as expected

**Comment by krupalivaghasiya24** [comment]
@Dimezis 
I tried **version-2.0.5** but getting this error **2.0.4 is working fine** for me

**implementation ("com.github.Dimezis:BlurView:version-2.0.5")**

Could not find com.github.Dimezis:BlurView:version-2.0.5.

**Comment by janbolat** [comment]
Build failed: https://jitpack.io/com/github/Dimezis/BlurView/version-2.0.5/build.log

**Comment by Dimezis** [comment]
@krupalivaghasiya24 
@janbolat 
Should be good now

**Comment by hmmmk** [comment]
@Dimezis any ideas on how to improve performance when using BlurView as BottomSheetDialogFragment background?

**Comment by Dimezis** [comment]
`RenderEffectBlur` should be more performant

**Comment by hmmmk** [comment]
@Dimezis okay, despite that, the issue is solved
